### ISSUE TITLE
Please add ValueFormatter to ColumnDef

### ISSUE THREAD

**Issue by latze123** [reflex-dev/reflex-ag-grid#11]
Hi Reflex team,
Thanks a lot for the Ag Grid implementation, it's very helpful! Would it be possible to also add the valueFormatter parameter for ColumnDef, please?
Displaying data in a grid looks so much better if its formatted properly.

https://www.ag-grid.com/javascript-data-grid/value-formatters/

Probably we could pass it something like this then (took it from a Discord discussion), which I use for formatting data in an rx.table already?

```
@var_operation
def two_decimal_points(value: NumberVar):
    return var_operation_return(
        js_expression=f"(new Intl.NumberFormat('de-DE', {{minimumFractionDigits: 2, maximumFractionDigits: 2}}).format({value}))",
        var_type=str,
    )
```

**Comment by Lendemor** [comment]
I think, from some previous experimentation, you can already pass `value_formatter` to column_def even if it's not defined (but it won't be suggested by pylance)

We'll try and add this soon.

**Comment by latze123** [comment]
Thanks for the swift reply @Lendemor !

Worked like this as part of column_def: `value_formatter="new Intl.NumberFormat('de-DE').format(value)"`

**Comment by skewed91** [comment]
@latze123, do you mind elaborating how you got it to work. I'm trying to format one of the columns as currency for instance ($1,234) and am struggling a bit.

**Comment by skewed91** [comment]
Thanks for the prompt response @latze123!

I get the following error using the code above:

ReferenceError: value is not defined

I'm not a JavaScript guy myself, so not sure how the ".format(value)" is supposed to work on the cell value!

Thanks!

**Comment by latze123** [comment]
Unfortunately can't help with that, as I don't know anything further about it - only can tell that my code (the original one with the cost centers) works for me. Sorry!

**Comment by Lendemor** [comment]
value_formatter is now a props of column_def so I'm closing this.
