### ISSUE TITLE
AG Grid Entreprise Not Importing Correctly

### ISSUE THREAD

**Issue by jellothere** [reflex-dev/reflex-ag-grid#9]
When trying to run Server Side Row Model I notice I get the following error. Dependencies seem to be set properly inthis wrapper but it still does not work. I can't spot where the issue is.

AG Grid: AG Grid: unable to use rowModelType = 'serverSide' as package 'ag-grid-enterprise' has not been imported. Check that you have imported the package:
            
    import 'ag-grid-enterprise';

**Comment by Lendemor** [comment]
Hi, can you provide a reproducible example of when you are using `rowModelType = 'serverSide'` ?

**Comment by jellothere** [comment]
In general, I have noticed that all enterprise features from ag grid do not work. Have you checked if they work for you? For example the side bar does not work either. When trying these out in node.js they work fine just some errors in the console regarding the license, but enterprise should be free to test out

**Comment by jellothere** [comment]
The issue is a version mismatch between ag-grid-enterprise and ag-grid-react. In ag_grid.py

class AgGrid(rx.Component):
    """Reflex AgGrid component is a high-performance and highly customizable component that wraps AG Grid, designed for creating rich datagrids."""

    # The library name for the ag-grid-react component
    library: str = "ag-grid-react@32.1.0"
    
    # ....
    
        lib_dependencies: list[str] = [
        "ag-grid-community@32.1.0",
        "ag-grid-enterprise@32.1.0",
    ]


The lib_dependencies should specify the same version as ag-grid-react.
